version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=library_admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  app:
    image: library:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library
      - SPRING_DATASOURCE_USERNAME=library_admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
